### PR TITLE
Fix image box shadow

### LINKED ISSUE #1720: Box Shadow Changes not visible in Editor View
### Description

The customer has reported this issue. When changing the box shadow of the blocks, the changes are not being visible in the Editor View properly and to see the changes, the user has to exit the editor view.

### Step-by-step reproduction instructions

1. Go to Edit Page.
2. Add any block for example, the image block or section or any other block.
3. Try changing the box shadow of the block and the change will not be visible in the Editor view.

### Screenshots, screen recording, code snippet or Help Scout ticket

Help Scout: https://secure.helpscout.net/conversation/2264389122/372067?folderId=212385

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1720 .

### Summary

Fix the Box Shadow image extension in Editor for Core Image.

### Screenshots 

image

----

### Test instructions

1. Create a core Image Block
2. In Inspector, activate the shadow in Box Shadow tab.
3. You should see the shadow in Editor.

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

File: src/blocks/plugins/image-extension/edit.js [hunk 1]
```diff
@@ -103,20 +103,17 @@ const Edit = ({
...
 
 	return (
 		<Fragment>
-			{ attributes.boxShadow ? (
-				<BlockEdit {...props } className={ props.className + ` ${cssNodeName};` } />
-			) : (
-				<BlockEdit {...props } className={ props.className + ` ${cssNodeName};` } />
-			) }
+
+			<BlockEdit {...props } className={ props.className + ` ${cssNodeName}` } />
```
Comment (HardeepAsrani) [inline src/blocks/plugins/image-extension/edit.js:116]: Shouldn't we just return <BlockEdit> without modifying the className if boxShadow isn't enabled?

Comment (Soare-Robert-Daniel) [reply src/blocks/plugins/image-extension/edit.js:116]: I see no need for it. It does not influence the frontend. And if we already created create the node, let's just use it.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel everything's working well 👍
