### PR TITLE
Fix infinite loop in Dynamic Content for Neve Custom Layout

### LINKED ISSUE #1600: Dynamic tags do not work with Neve PRO custom layouts
### Description

Inserting dynamic tag into Neve PRO Custom Layout is not possible, gives an error when saving:
image

### Step-by-step reproduction instructions

- Go to layouts, create a new layout
- Choose post template
- Name the template
- Add dynamic title, content and featured image. (actually, adding any dynamic tag is enough - https://docs.themeisle.com/article/1677-dynamic-values )
- Add conditonal logic "post type is equal to something
- Try to save

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2189970724/362599

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1600.

### Summary

Sanitize the page's content when using Dynamic Content by removing references to dynamic content tags.

### Screenshots 

https://user-images.githubusercontent.com/17597852/231764637-c975ebbb-ba15-4f3a-b23a-df3b094d065c.mp4

----

### Test instructions

1. Make a custom layout like it is mentioned in the issue.
2. When adding Dynamic Content, no error should appear in Editor.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and the issue is not fixed for me:

I created a custom layout where i used dynamic tags for `Title, Content, Id, Excerpt` and got the same error in [editor](https://vertis.d.pr/i/zG66D3). In frontend, the content is missing and everything is duplicated https://vertis.d.pr/i/hEznFd . Also, if i use only the `Post content` tag, saving the custom layout is working but nothing is visible in frontend https://vertis.d.pr/i/Ccj9Wq

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, one reliable solution so far is to stop the usage of function that cause infinite loops: `wp_trim_excerpt`, `get_the_content`.

I added a function that mark if the Dynamic Request is an exception. I tried to make the function as hook, but failed (it return `null` I do not why`.

Do you think we should put some warning in Editor to inform the user that `post content` and `post excerpt` will do nothing in the page when their inserted in a non Query Loop?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Based on that, where exactly will it not work? Will it work with Neve Custom Layouts and FSE? We don't need to add any notices in case it doesn't work in places where it _shouldn't_ work, as in it can cause an infinite loop.

**Comment by Soare-Robert-Daniel** [comment]
In Neve Custom Layout is working as long you do not put them directly in a block that is not Query Loop -- this triggers an infinite loop. 

As long the processing does not require to re-process its own content, it works fine. And we should enforce this.

File: inc/plugins/class-dynamic-content.php [hunk 1]
```diff
@@ -649,6 +663,53 @@ public function get_link( $data ) {
 		return apply_filters( 'otter_blocks_evaluate_dynamic_content_link', '', $data );
 	}
 
+	/**
+	 * Mark the exceptions for Dynamic request.
+	 *
+	 * @param array $data Dynamic request.
+	 * @return array Dynamic request with marked exceptions.
+	 */
+	public function mark_exceptions( $data ) {
```
Comment (selul) [inline inc/plugins/class-dynamic-content.php:672]: NIT, it might be more relevant to keep this code in Neve, i.e. have some filter and hook this exception in Neve since it's compatibility for Otter vs. the way around.

Comment (HardeepAsrani) [reply inc/plugins/class-dynamic-content.php:672]: Yea, I agree with both in this, but I do expect that this problem can happen in just any plugin that does this, so it's more of an Otter problem than Neve.

**Comment by Soare-Robert-Daniel** [comment]
After more testing, the Widgets and FSE are safe:

- On Widgets, the `postContent` is just copying the content of page without feeding the widget itself.
- On FSE, the page appears duplicated, as expected, with no infinite loop.

---

In the docs, we should make a section about those edge cases https://docs.themeisle.com/article/1677-dynamic-values , adding some mentions like:

- `Post Content` and `Post Excerpt ` should be used inside the Query Loop block. 
- ⚠️  Adding them in a non-Query Loop block might create unwanted behavior.

---

Another improvement might be adding a Go to Docs in that popup of Dynamic Content. Dynamic Content tags can be inserted anywhere, but we should create the impression that they work in every possible situation without some quirks.

Regarding the one with Neve Custom Layout is very bad since it may stop the page from rendering in Frontend.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and it works fine now, when used inside the Query loop. I also noticed that the dynamic tags work when they are placed **after** a query loop block, not necessarily inside it https://vertis.d.pr/i/k6pgLY . 

Besides this, i think we should also inform the user that Post content and excerpt tags don't work without the Query loop, because the page won't load in frontend and they might think it's a problem on our end.

Let me know your thoughts on this 👍

File: inc/plugins/class-dynamic-content.php [hunk 2]
```diff
@@ -649,6 +662,84 @@ public function get_link( $data ) {
...
+
+			if ( 'postContent' === $data['type'] ) {
+				$content = get_the_content( $data['context'] );
+				if ( strpos( $content, 'data-type="postContent"' ) ) {
+					$key = $this->get_exception_key( $data, $post->ID );
+					if ( $key ) {
+						$data[ $key ] = true;
+					}
+				}
+			}
```
Comment (Soare-Robert-Daniel) [inline inc/plugins/class-dynamic-content.php:697]: This should prevent the following situation:
Screenshot 2023-04-26 at 15 18 44

We will not process that still has the dynamic tag since it triggers the infinite loop.

**Review by HardeepAsrani — APPROVED** [review]
We can get another round of QA. The changes look fine to me but let's see if they will work. If not then we can revisit this after other stuff with a fresh outlook and setup some tests first to avoid further back and forth with QA/CodeReview/Rework

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Had another look and it works fine 👍
