### PR TITLE
[Rock] Add PHP unit tests

### LINKED ISSUE #1623: Identify and expand Unit testing
### What problem does this address?

Compared to other products in the company, Otter lacks unit tests. We can identify a few areas where we can expand with unit tests. We can target for:

- Quick & easy gains.
- Features prone to bugs/regressions.

### What is your proposed solution?

Here are a few that I think can be part:

- Block Conditions
- Dynamic Content
- Forms
- Stripe

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1623

### Summary

Added units tests for:
- Dynamic Content query parse and small evaluation test
- Dynamic Conditions evaluation
- Stripe_API functions unit test
- Pro Patterns fetching test

Locally the test can be run with Docker provided by Gutenberg packages.
```bash
npm run test:unit:php:setup # start the container
npm run test:unit:php:base # run the tests from `./tests` folder
```

### Test instructions

1. A slight change was made in Dynamic Content. Have a test instance with the current version, and after switching with the one from this PR, check if it still works.
2. Same with Stripe -> check Stripe Checkout Block

---- 

### Checklist before the final review

- [x] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Can you fix the failing tests before putting it for review? Also, why do we have two separate unit tests actions?

**Comment by Soare-Robert-Daniel** [comment]
I removed the old method. The old method was installing the test instance on the local machine. The new one will use a docker test instance provided by `wp-env` and `wp-scripts`.

File: tests/test-stripe-api-class.php [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+	/**
+	 * Set up the test.
+	 */
+	public function set_up() {
+		parent::set_up();
+
+		if ( ! defined( 'OTTER_BLOCKS_VERSION' ) ) {
+			define('OTTER_BLOCKS_VERSION', '1.0.0');
+		}
```
Comment (HardeepAsrani) [inline tests/test-stripe-api-class.php:34]: Just a NIT, we can move this to the bootstrap class to avoid having to redefine it in some other test in future.

**Review by HardeepAsrani — APPROVED** [review]
LGTM, I've left a NIT but it looks good. We should get a good QA done on these features, Block Conditions in particular as I see there is some code change there to confirm that everything works just like before.

File: tests/test-stripe-api-class.php [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+/**
+ * Class TestStripeAPI
+ *
+ * @package Your_Plugin_Name
+ */
+
+use ThemeIsle\GutenbergBlocks\Plugins\Stripe_API;
+use ThemeIsle\GutenbergBlocks\Tests\StripeHttpClientMock;
+
+// Replace with the correct namespace from your uploaded file.
```
Comment (HardeepAsrani) [inline tests/test-stripe-api-class.php:11]:
```suggestion
```

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and everything's fine on my end 🚀
