### PR TITLE
Evergreen Reset Fix

### LINKED ISSUE #1377: Improve Countdown evergreen.
### Description:

Make the Evergreen mode a proper evergreen mode.

### Expected behavior:

The countdown should reset with each refresh.

### Current behavior:

The countdown acts like a Timer. Once the time is over, the time is shown as 0.

### Technical info
* WordPress version: latest
* Plugin version: latest

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1377 .

### Summary

Add a fix for Evergreen reset and docs.

### Screenshots 

----

### Test instructions

1. Add a Countdown with the mode Evergreen
2. Set the time, then preview.
3. Test time reset on __refresh__, which has the conditions:
    1. Time is over.
    2. Timezone has changed 
    3. Deadline has changed.

If you think the time should have reset in a situation that is not mentioned, please post the scenario 🙏 .

For Timezone, you can use the Sensor tab from the browser Dev Tools (Chrome)
image

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

File: src/blocks/frontend/countdown/index.ts [hunk 1]
```diff
@@ -105,42 +115,50 @@ class CountdownData {
...
+			 * - the timezone has changed
+			 */
 			if (
 				! lastVisitTimeRecord ||
-				( ( parseInt( lastVisitTimeRecord ) + parseInt( this.timer ) - Date.now() ) > COUNTDOWN_RESET ) ||
-				timerValueRecorded !== this.timer
+				( 0 > ( parseInt( lastVisitTimeRecord ) + parseInt( this.timer ) - Date.now() ) ) ||
+				timerValueRecorded !== this.timer ||
+				timezoneRecorded != ( new Date() ).getTimezoneOffset().toString()
 			) {
```
Comment (Soare-Robert-Daniel) [inline src/blocks/frontend/countdown/index.ts:154]: @HardeepAsrani, do you think we need more conditions beside those?

Comment (HardeepAsrani) [reply src/blocks/frontend/countdown/index.ts:154]: Seems good enough to me.

Comment (HardeepAsrani) [reply src/blocks/frontend/countdown/index.ts:154]: You can put it in QA if you're satisfied with the rest. And if you want we can test on the themeisle website to test.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and everything's fine for me 👍
