### PR TITLE
Fix Neve Custom Layout CSS

### LINKED ISSUE #1436: Popup block styles not loading when used in a Neve Custom Layout context
### Description:

As discussed before, Otter should work as expected when used in a Custom layout context, as it's opens a new - global way of building things. Just to mention two use-cases for this, one is building a Popup that will show side-wide, or building a Countdown that will show side-wide. 
___
In this case I tried building a Popup inside a Custom Layout and display it site-wide.
When the Popup is used on a single page (directly inserted in the markup) - it works as expected. But when used in a Custom Layout context, the Popup will look shrinked (attached images).

### How to reproduce:

1. I used a modified version of [Web Agency Demo](https://demosites.io/web-agency-gb/)
2. and added this Popup in a site wide Custom Layout
[popup.json.zip](https://github.com/Codeinwp/otter-blocks/files/10382450/popup.json.zip)

### Expected behaviour:
image (1)

### Current behaviour:
image (2)

### Reference:

image (3)

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.1.6
* Neve: 3.4.10
* Neve Pro: 2.4.9

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1436 .

### Summary

Tweak the hooks that generate the dynamic CSS.

### Screenshots 

Setup

image

Without fix

image

With fix

image

----

### Test instructions

1. Make a Custom Neve Layout with Otter Blocks and add the option Global (so it can show up in any page)
2. Check the pages and see if the CSS is working.
3. Since this is a tweak in pipeline, it is recommended to check Widgets and FSE for regressions.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, we have two actions for CSS generation function:

https://github.com/Codeinwp/otter-blocks/blob/26261cbd3f517621fe5bf73fdbacf9efa4778741/inc/class-registration.php#L332-L346

Do you think we can only use the `wp_footer` action? Is the filter `the_content` used in some situations where `wp_footer` is not?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel It's been quite sometime so I don't remember exactly why but as far as I recall the issue was that in some certain situation it was too late for wp_footer, I think for archive pages.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Maybe you can add a comment there for future self so we know why that part is there.

File: inc/class-registration.php [hunk 1]
```diff
@@ -338,6 +338,13 @@ function ( $content ) {
 			}
 		);
 
+		add_action(
+			'wp_footer',
+			function() {
```
Comment (selul) [inline inc/class-registration.php:343]: Here won't this include the style on all pages, ignoring the previous conditions the previous conditions?

**Review by selul — CHANGES_REQUESTED** [review]

File: inc/class-registration.php (hunk 1 above)
Comment (HardeepAsrani) [reply inc/class-registration.php:343]: No because if something has been enqueued already, it won't try to enqueue it again, we've conditions to make sure of that. This entire CSS enqueue is pretty ad-hoc as WordPress kept adding new things Widgets, Query, FSE and so on. While it works, it's not an ideal solution and there's a ticket to write CSS enqueue part from scratch to rethink the whole thing: https://github.com/Codeinwp/otter-blocks/issues/1081

Those different places take care of different scenarios, and one takes care for those that weren't already enqueued. Each is fail-safe for other. It's a mess but it works in all cases so far and nothings get enqueued twice.

Comment (HardeepAsrani) [reply inc/class-registration.php:343]: But that's for the entire existing solution, the wp_footer solution isn't ideal and we should find others way to deal with this than to use wp_footer.

Comment (HardeepAsrani) [reply inc/class-registration.php:343]: @Soare-Robert-Daniel We should use some action in Custom Layout to trigger the CSS as it might be used in various different ways.

Comment (HardeepAsrani) [reply inc/class-registration.php:343]: As if it's added to a hook or outside post context, our filter won't realize it's a post type.

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
As mentioned in the comments previously, we can do without `wp_footer` call. There are already a lot of fail safes there, this one doesn't feel necessary. At least we should explore other options first.

**Comment by Soare-Robert-Daniel** [comment]
The main problem is the content that is received from Neve Custom Layout. The content is stripped from Gutenberg Markup, thus making it invisible for our pipeline processing.

What we need to receive:

```html
<!-- wp:themeisle-blocks/popup {"id":"wp-block-themeisle-blocks-popup-8b7ac685","backgroundColor":"var(\u002d\u002dnv-secondary-accent)","overlayColor":"#385541","overlayOpacity":81} -->
<div id="wp-block-themeisle-blocks-popup-8b7ac685" class="wp-block-themeisle-blocks-popup is-front" data-dismiss="" data-time="0" data-anchor="" data-offset="" data-outside="true" data-anchorclose=""><div class="otter-popup__modal_wrap"><div role="presentation" class="otter-popup__modal_wrap_overlay"></div><div class="otter-popup__modal_content"><div class="otter-popup__modal_header"><button type="button" class="components-button has-icon"><svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" role="img" aria-hidden="true"><path d="M12 13.06l3.712 3.713 1.061-1.06L13.061 12l3.712-3.712-1.06-1.06L12 10.938 8.288 7.227l-1.061 1.06L10.939 12l-3.712 3.712 1.06 1.061L12 13.061z"></path></svg></button></div><div class="otter-popup__modal_body"><!-- wp:paragraph {"backgroundColor":"nv-c-1","textColor":"nv-c-2","fontSize":"x-large"} -->
<p class="has-nv-c-2-color has-nv-c-1-background-color has-text-color has-background has-x-large-font-size">Bonsoir</p>
<!-- /wp:paragraph --></div></div></div></div>
<!-- /wp:themeisle-blocks/popup -->
```

What do we get

```html
<div id="wp-block-themeisle-blocks-popup-8b7ac685" class="wp-block-themeisle-blocks-popup is-front" data-dismiss="" data-time="0" data-anchor="" data-offset="" data-outside="true" data-anchorclose=""><div class="otter-popup__modal_wrap"><div role="presentation" class="otter-popup__modal_wrap_overlay"></div><div class="otter-popup__modal_content"><div class="otter-popup__modal_header"><button type="button" class="components-button has-icon"><svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" role="img" aria-hidden="true"><path d="M12 13.06l3.712 3.713 1.061-1.06L13.061 12l3.712-3.712-1.06-1.06L12 10.938 8.288 7.227l-1.061 1.06L10.939 12l-3.712 3.712 1.06 1.061L12 13.061z"></path></svg></button></div><div class="otter-popup__modal_body">
<p class="has-nv-c-2-color has-nv-c-1-background-color has-text-color has-background has-x-large-font-size">Bonsoir</p>
</div></div></div></div>
```

**Comment by Soare-Robert-Daniel** [comment]
The previous observation is irrelevant to this issue since the function `has_block` correctly detects the block without the given content.

The issue is with the hook that generated the CSS. 
https://github.com/Codeinwp/otter-blocks/blob/2d1252fe0ef867296cb67e491026c12d613de54a/inc/class-blocks-css.php#L32

This hook is not called when Neve hooks generate the output.

**Comment by Soare-Robert-Daniel** [comment]
Putting the `'render_server_side_css'` in `wp_footer` hook with the lowest priority help to trigger it.

But our CSS generator only takes into consideration the content from the post. Anything from outside is ignored.

https://github.com/Codeinwp/otter-blocks/blob/2d1252fe0ef867296cb67e491026c12d613de54a/inc/class-blocks-css.php#L113

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I did some testing and I think it can be fixed by increasing the priority of the wp_footer calls in this function: https://github.com/Codeinwp/otter-blocks/blob/865b9017d4be50f3d0af2dbab4e662548af3bfcb/inc/css/class-block-frontend.php#L262 - just doing that should solve it.

And for the last call (that tries to enqueue the style if CSS size condition isn't met, you can remove wp_footer and see if this changes how other pages work.

Not an idea but a good solution for now, we can prioritize the CSS class once Form stuff is done to simplify CSS loading mess.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, your proposed solution does not work on my end.

A solution that I found to be working is this:

1. Make a filter that collects the content from all the sources via `the_content` with priority 0. Also, removing the duplicates.

https://github.com/Codeinwp/otter-blocks/blob/7d2a3218e7ccde86c362fea584445f8a8eee3ba7/inc/css/class-block-frontend.php#L653-L682

2. At the end, on `wp_footer`, process the collected content and extract the CSS.

https://github.com/Codeinwp/otter-blocks/blob/7d2a3218e7ccde86c362fea584445f8a8eee3ba7/inc/css/class-block-frontend.php#L684-L705

You check in page with this: `document.querySelector('#otter-neve-layout-solution')`

This is working with Neve Custom Layouts and Query Loop

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and the issue is not entirely fixed:

- [ ] The font awesome icons are not visible on the Shop archives, Blog archive and Single posts https://vertis.d.pr/v/ayzKZJ

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, the FA are detected, but it seems that dependency is not loaded on the page

https://github.com/Codeinwp/otter-blocks/blob/b82d5d670184001e2125b67614b2cb4838e22efa/inc/class-registration.php#L89-L90 

This hook trigger correctly but without effect.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Checked again and everything works fine now, thank you 👍
